- name: apply common configruation to all nodes
  hosts: all 
  remote_user: django 
  become: yes
  become_user: root
  roles:
      - common

- name: deploy postgreSQL and configure the database
  hosts: all
  remote_user: django 
  become: yes
  become_user: root
  roles:
      - role: database 
  tags:
      - database

- name: configure and deploy django infrastructure and application code 
  hosts: all 
  remote_user: django 
  roles:
      - role: web
  tags:
      - webapp 

